//go:build !ignore_autogenerated

/*
This file was generated with "make generate-deepcopy".
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisplayName) DeepCopyInto(out *DisplayName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisplayName.
func (in *DisplayName) DeepCopy() *DisplayName {
	if in == nil {
		return nil
	}
	out := new(DisplayName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpMenuEntry) DeepCopyInto(out *WarpMenuEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpMenuEntry.
func (in *WarpMenuEntry) DeepCopy() *WarpMenuEntry {
	if in == nil {
		return nil
	}
	out := new(WarpMenuEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpMenuEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpMenuEntryList) DeepCopyInto(out *WarpMenuEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpMenuEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpMenuEntryList.
func (in *WarpMenuEntryList) DeepCopy() *WarpMenuEntryList {
	if in == nil {
		return nil
	}
	out := new(WarpMenuEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpMenuEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpMenuEntrySpec) DeepCopyInto(out *WarpMenuEntrySpec) {
	*out = *in
	out.DisplayName = in.DisplayName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpMenuEntrySpec.
func (in *WarpMenuEntrySpec) DeepCopy() *WarpMenuEntrySpec {
	if in == nil {
		return nil
	}
	out := new(WarpMenuEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpMenuEntryStatus) DeepCopyInto(out *WarpMenuEntryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpMenuEntryStatus.
func (in *WarpMenuEntryStatus) DeepCopy() *WarpMenuEntryStatus {
	if in == nil {
		return nil
	}
	out := new(WarpMenuEntryStatus)
	in.DeepCopyInto(out)
	return out
}
