// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-warp-menu-entry-lib/api/v1"
	apiv1 "github.com/cloudogu/k8s-warp-menu-entry-lib/client/typed/api/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeWarpMenuEntries implements WarpMenuEntryInterface
type fakeWarpMenuEntries struct {
	*gentype.FakeClientWithList[*v1.WarpMenuEntry, *v1.WarpMenuEntryList]
	Fake *FakeApiV1
}

func newFakeWarpMenuEntries(fake *FakeApiV1, namespace string) apiv1.WarpMenuEntryInterface {
	return &fakeWarpMenuEntries{
		gentype.NewFakeClientWithList[*v1.WarpMenuEntry, *v1.WarpMenuEntryList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("warpmenuentries"),
			v1.SchemeGroupVersion.WithKind("WarpMenuEntry"),
			func() *v1.WarpMenuEntry { return &v1.WarpMenuEntry{} },
			func() *v1.WarpMenuEntryList { return &v1.WarpMenuEntryList{} },
			func(dst, src *v1.WarpMenuEntryList) { dst.ListMeta = src.ListMeta },
			func(list *v1.WarpMenuEntryList) []*v1.WarpMenuEntry { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.WarpMenuEntryList, items []*v1.WarpMenuEntry) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
