// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	apiv1 "github.com/cloudogu/k8s-warp-menu-entry-lib/api/v1"
	scheme "github.com/cloudogu/k8s-warp-menu-entry-lib/client/scheme"
	rest "k8s.io/client-go/rest"
)

type ApiV1Interface interface {
	RESTClient() rest.Interface
	WarpMenuEntriesGetter
}

// ApiV1Client is used to interact with features provided by the api group.
type ApiV1Client struct {
	restClient rest.Interface
}

func (c *ApiV1Client) WarpMenuEntries(namespace string) WarpMenuEntryInterface {
	return newWarpMenuEntries(c, namespace)
}

// NewForConfig creates a new ApiV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ApiV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ApiV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ApiV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ApiV1Client{client}, nil
}

// NewForConfigOrDie creates a new ApiV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ApiV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ApiV1Client for the given RESTClient.
func New(c rest.Interface) *ApiV1Client {
	return &ApiV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ApiV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
