// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-warp-menu-entry-lib/api/v1"
	scheme "github.com/cloudogu/k8s-warp-menu-entry-lib/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WarpMenuEntriesGetter has a method to return a WarpMenuEntryInterface.
// A group's client should implement this interface.
type WarpMenuEntriesGetter interface {
	WarpMenuEntries(namespace string) WarpMenuEntryInterface
}

// WarpMenuEntryInterface has methods to work with WarpMenuEntry resources.
type WarpMenuEntryInterface interface {
	Create(ctx context.Context, warpMenuEntry *apiv1.WarpMenuEntry, opts metav1.CreateOptions) (*apiv1.WarpMenuEntry, error)
	Update(ctx context.Context, warpMenuEntry *apiv1.WarpMenuEntry, opts metav1.UpdateOptions) (*apiv1.WarpMenuEntry, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, warpMenuEntry *apiv1.WarpMenuEntry, opts metav1.UpdateOptions) (*apiv1.WarpMenuEntry, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.WarpMenuEntry, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apiv1.WarpMenuEntryList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiv1.WarpMenuEntry, err error)
	WarpMenuEntryExpansion
}

// warpMenuEntries implements WarpMenuEntryInterface
type warpMenuEntries struct {
	*gentype.ClientWithList[*apiv1.WarpMenuEntry, *apiv1.WarpMenuEntryList]
}

// newWarpMenuEntries returns a WarpMenuEntries
func newWarpMenuEntries(c *ApiV1Client, namespace string) *warpMenuEntries {
	return &warpMenuEntries{
		gentype.NewClientWithList[*apiv1.WarpMenuEntry, *apiv1.WarpMenuEntryList](
			"warpmenuentries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1.WarpMenuEntry { return &apiv1.WarpMenuEntry{} },
			func() *apiv1.WarpMenuEntryList { return &apiv1.WarpMenuEntryList{} },
		),
	}
}
